### ISSUE TITLE
Use distinct names for CompressionAlgorithm enums

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#1049]
At the moment we have two:

https://github.com/TraceMachina/nativelink/blob/97abbcd24b4f87f500f6ab2d9898b4a8401d9f3b/nativelink-config/src/stores.rs#L669-L680

https://github.com/TraceMachina/nativelink/blob/97abbcd24b4f87f500f6ab2d9898b4a8401d9f3b/nativelink-config/src/cas_server.rs#L35-L44

This confuses doc generators and introduces unnecessary complexity. We should unify them to a single `CompressionAlgorithm` and handle unsupported cases in consumers.

*Edit:* From the conversation it seems like the easiest short-term fix is to just give the two different enums distinct names.

**Comment by allada** [comment]
Yeah, I remember this when implementing it.

These technically are not the same thing. I do think we should rename them, but I'm not convinced we can unify them.

The one with `gzip` is for HTTP translations, but `lz4` is for store translations. This matters because we don't use `lz4`'s container format because it lacks some optimizations we use, instead we only use the compression algorithm. Our `lz4` can take parameters, where `gzip` cannot.

`gzip` is a specific spec we must honor and we let `hyper` deal with it.

**Comment by aaronmondal** [comment]
I see. I guess a rename is best then :+1:
