### ISSUE TITLE
`docker-compose` Example does not appear to work

### ISSUE THREAD

**Issue by swarren12** [TraceMachina/nativelink#1484]
**Expected behaviour**: I can run the `docker-compose` example and get a basic remote executor
**Actual behaviour**: I run the `docker-compose` example and get a remote cache, but not a remote executor

**More details**

**Operating System**: Fedora 40
**Nativelink version**: cloned from repository @ `main`
**Bazel version**: 7.4.0

**Steps to reproduce:**

First, I clone the main `nativelink` repository and run the `docker-compose` example:

```
$ git clone https://github.com/TraceMachina/nativelink.git 
$ cd nativelink
$ cd deployment-examples/docker-compose
$ docker compose up
...
[+] Running 3/0
 ✔ Container docker-compose-nativelink_executor-1   Created                                                                                                                                                                                           0.0s 
 ✔ Container docker-compose-nativelink_local_cas-1  Created                                                                                                                                                                                           0.0s 
 ✔ Container docker-compose-nativelink_scheduler-1  Created    
...
nativelink_executor-1   |   2024-11-19T10:05:42.072224Z  WARN nativelink_worker::local_worker: Worker registered with scheduler, worker_id: bb31df10-6cd3-42ca-a3e8-179d0a5b91a8
nativelink_executor-1   |     at nativelink-worker/src/local_worker.rs:571
nativelink_executor-1   |     in nativelink::worker with name: "worker_0"
nativelink_executor-1   | 
```

Then, in a Bazel project, I add:
```
build --remote_cache=grpc://127.0.0.1:50051
build --remote_executor=grpc://127.0.0.1:50052
build --remote_default_exec_properties=cpu_count=1
```

I then run `bazel info` and get the following error:
```
ERROR: Failed to query remote execution capabilities: Remote execution is not supported by the remote server, or the current account is not authorized to use remote execution.
java.io.IOException: Remote execution is not supported by the remote server, or the current account is not authorized to use remote execution.
        at com.google.devtools.build.lib.remote.GoogleChannelConnectionFactory.lambda$getAndVerifyServerCapabilities$4(GoogleChannelConnectionFactory.java:140)
```

and the `docker compose` log shows:
```
nativelink_local_cas-1  |   2024-11-19T10:05:59.839600Z ERROR nativelink::services: Failed running service, err: hyper::Error(Io, Kind(NotConnected))
nativelink_local_cas-1  |     at src/bin/nativelink.rs:855
nativelink_local_cas-1  |     in nativelink::services::http_connection with remote_addr: xxx.xxx.xxx.xxx:41694, socket_addr: 0.0.0.0:50051
```

I've tried changing the Rust logging level from `warn` to `debug` and then when I run `bazel info` I see:

```
nativelink_scheduler-1  |   2024-11-19T10:12:27.724568Z  INFO nativelink_service::capabilities_server: return: Response { metadata: MetadataMap { headers: {} }, message: ServerCapabilities { cache_capabilities: Some(CacheCapabilities { digest_functions: [Sha256, Blake3], action_cache_update_capabilities: Some(ActionCacheUpdateCapabilities { update_enabled: true }), cache_priority_capabilities: None, max_batch_total_size_bytes: 65536, symlink_absolute_path_strategy: Disallowed, supported_compressors: [], supported_batch_update_compressors: [] }), execution_capabilities: None, deprecated_api_version: None, low_api_version: Some(SemVer { major: 2, minor: 0, patch: 0, prerelease: "" }), high_api_version: Some(SemVer { major: 2, minor: 3, patch: 0, prerelease: "" }) }, extensions: Extensions }
nativelink_scheduler-1  |     at nativelink-service/src/capabilities_server.rs:94
nativelink_local_cas-1  |   2024-11-19T10:12:27.724570Z  INFO nativelink_service::capabilities_server: return: Response { metadata: MetadataMap { headers: {} }, message: ServerCapabilities { cache_capabilities: Some(CacheCapabilities { digest_functions: [Sha256, Blake3], action_cache_update_capabilities: Some(ActionCacheUpdateCapabilities { update_enabled: true }), cache_priority_capabilities: None, max_batch_total_size_bytes: 65536, symlink_absolute_path_strategy: Disallowed, supported_compressors: [], supported_batch_update_compressors: [] }), execution_capabilities: None, deprecated_api_version: None, low_api_version: Some(SemVer { major: 2, minor: 0, patch: 0, prerelease: "" }), high_api_version: Some(SemVer { major: 2, minor: 3, patch: 0, prerelease: "" }) }, extensions: Extensions }
```
... specifically: `execution_capabilities: None`.

Additionally, if I remove the `build --remote_executor=grpc://127.0.0.1:50052` line and try to build, the console log is flooded with the following errors:

```
nativelink_local_cas-1  |   2024-11-19T10:15:17.109353Z ERROR nativelink_service::ac_server: return: Err(Error { code: Internal, messages: ["'instance_name' not configured for ''"] })
```

I'm assuming that there's something wrong with the default example configuration, but I've yet to be able to narrow down exactly what it is.

**Comment by MarcusSorealheis** [comment]
@swarren12 thank you for reporting the issue. We are reading the thorough write up which we appreciate and will look to respond as soon as possible.

**Comment by MarcusSorealheis** [comment]
Two questions I have right away are:

What are the specs of the machine on which you are running this test? OS, version, Docker version, Chip, etc. 

Why did you attempt to run Docker Compose on main rather than a released version? I'm expecting it to be a bit unstable as we only guarantee stability of releases.

**Comment by aaronmondal** [comment]
@swarren12 Could you try running the commands with an additional `--remote_instance_name=main` flag? The instance name is configured here (and again a few lines lower): https://github.com/TraceMachina/nativelink/blob/481226be52a84ad5a6b990cc48e9f97512d8ccd2/deployment-examples/docker-compose/scheduler.json#L43

If you don't set the `--remote_instance_name` flag, it expects an empty string (i.e. you could also use `""` instead of `"main"` in the configs if you don't want to use the flag).

@swarren12 If this solves your issue, I think we should remove the "main" from the configs and actually use empty strings by default as this has been a point of confusion in the past. Would you be interested in sending a PR for this?

**Comment by swarren12** [comment]
> @swarren12 Could you try running the commands with an additional `--remote_instance_name=main` flag? The instance name is configured here (and again a few lines lower):
> 
> https://github.com/TraceMachina/nativelink/blob/481226be52a84ad5a6b990cc48e9f97512d8ccd2/deployment-examples/docker-compose/scheduler.json#L43
> 
> If you don't set the `--remote_instance_name` flag, it expects an empty string (i.e. you could also use `""` instead of `"main"` in the configs if you don't want to use the flag).
> 
> @swarren12 If this solves your issue, I think we should remove the "main" from the configs and actually use empty strings by default as this has been a point of confusion in the past. Would you be interested in sending a PR for this?

This appears to work. I'll run a few more tests later today and look at raising a PR if everything looks good.

Thanks!

**Comment by swarren12** [comment]
@aaronmondal I noticed that the other examples (K8s, Chromium) are located under `deploy/...-example`, whilst `docker-compose` is `deployment-example/docker-compose`. Do you think it should be moved to `deploy/docker-compose-example`?

**Comment by aaronmondal** [comment]
@swarren12 The idea behind the current directory layout is

- `kubernetes`: The "building blocks" for deployments on K8s
- `deploy`: The actual thing you'd invoke with kustomize/K8s. These reach into the `kubernetes` directory to construct the yaml files that are ultimately deployed to the cluster. The reason this is at the top level is so that we get the nicer looking `kubectl` command in the [k8s guide](https://www.nativelink.com/docs/deployment-examples/kubernetes#%EF%B8%8F-prepare-the-cluster). Also, this way we can modify the `deploy/dev/kustomization.yaml` and use `kubectl apply -k deploy/dev` when we develop new functionality against k8s.

If we want to keep the "ideas" behind this structure, the initial thought that would come to mind is to have a top-level `docker-compose` directory that contains the internal logic for the docker-compose example, and then add the deployment logic to the `deploy` example. However, this would overcomplicate the example unnecessarily, as it's much simpler than the K8s deployments.

So my suggestion would actually be to just remove the intermediary `deployment-examples` directory altogether and to just move the `docker-compose` directory to the top-level. A similar commit intended to rename `deployment-examples` to `examples`, but thinking more about this it seems to me that the best UX would be to remove the unnecessary directory nesting.

A potentially relevant note here is that we need to move the docker-compose example to the [graveyard](https://github.com/TraceMachina/graveyard) at some point because it encourages bad practices (it's irreproducible, containers are way too large, we can't create fully mapped-out SBOMs, it's actually a misleading example since the usecases it shows would be better handled by a single container image with all-in-one cas/scheduler/worker, the list goes on), and the integration tests running against the example are very flaky. However, we first need to migrate the integration tests to the K8s workflows so that we don't regress our end-to-end testing coverage.

Something that might be more valuable here in general would be to "merge" the configs from the current docker-compose example into a single one and create a new example without docker-compose that achieves the same thing with a single image. The split architecture is only necessary for autoscaling and high-availability requirements in K8s.

**Comment by swarren12** [comment]
That makes sense. I've limited my change to just remove `"main"` from the `docker-compose.yaml` and will leave the wider restructuring to someone with better context for when that would be appropriate to do. I noticed that _only_ changing the `docker-compose` file caused some integration tests to fail, so I figure any restructuring would also impact those, and that suggests to me it would be better done as a dedicated PR.
