### ISSUE TITLE
Custom containerized workers

### ISSUE THREAD

**Issue by Whoaa512** [TraceMachina/nativelink#313]
Hey thanks for working on this!

I was curious if it's possible to execute a worker action within a specified docker image.

Currently we have a base image that contains system dependencies not yet modeled in bazel. We have a small wrapper that pulls or builds that base image and then executes our bazel build within it.

From looking through the examples, it didn't seem like this was possible yet but hoping I missed it :)

**Comment by allada** [comment]
Yes, currently the way to do this is to use `[entrypoint_cmd](https://github.com/TraceMachina/turbo-cache/blob/93572d1aac11a93a50758d6f1f8bc9db5b0011c0/config/cas_server.rs#L282)` in the config and sniff out this data.

You can get TurboCache to inject the docker image into the build through `platform_properties` and present it as an environ to the wrapper.

Here's an example that also has some "gotcha" checks for docker:
https://gist.github.com/allada/0f6bbf0c3fa87d6dcdbd6a9a3bc4135b

We do have plans on making this more "native", however we want to make sure we do it right, since adding native containerization will add a significant amount of technical debt.

A little bit has been discussed here about it: https://github.com/TraceMachina/turbo-cache/issues/225 , but since there is a "work around", it has not been a huge priority.

**Comment by allada** [comment]
If you are concerned about docker entry/exit penalties in the example listed above, the simple solution around it is to simply launch the worker inside a docker container, however be warned that this is significantly less hermetic.

**Comment by Whoaa512** [comment]
Awesome, thanks for the pointers!

**Comment by MarcusSorealheis** [comment]
@Whoaa512 are you all set here? I can help out if you need a hand.

**Comment by aaronmondal** [comment]
FYI there is now also [local-remote-execution](https://github.com/TraceMachina/nativelink/tree/main/local-remote-execution) which might give some pointers on how to set up containers with nativelink in them.

The gist of it is
1. Create the container
2. Mount nativelink into the container or create some merged docker image of the toolchain container and nativelink
3. Generate toolchain configs for your ruleset.
4. Hook the toolchains and platforms into your build.

The (kubernetes example)[https://github.com/TraceMachina/nativelink/tree/main/deployment-examples/kubernetes] has configs that make use of such a custom container.

**Comment by aaronmondal** [comment]
#728 and the follow-up #730 make the process of creating custom worker images a bit more "standardized". The docs for the `kubernetes-classic` example go into more detail on how custom containers can be matched to corresponding platforms via platform properties.

**Comment by aaronmondal** [comment]
There is now a new `nativelink-worker-init` image that can be used in K8s deployments to extend any arbitrary toolchain container with nativelink:

- https://github.com/TraceMachina/nativelink/commit/00e5bb3406505bff561ef3c53db2d69d621b7559

Closing this since I believe this is now a fixed issue. Let me know if there are any additional issues/questions regarding this and we can reopen this or create a new issue.
